[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
<<<<<<< HEAD
	command = "npm run build"
	publish = "_site"

	[dev]
	publish = "public"
=======
publish = ".next"
>>>>>>> a9746bc8f74e3163720dd379c067d4f8f30d406b

